### ISSUE TITLE
Only sms 

### ISSUE THREAD

**Issue by Amolmeh** [utsanjan/Tsunami-Bomber-Android#1]
It has only sms feature no call ?

**Comment by utsanjan** [comment]
The SMS and call OTP feature both worked quite fine, but due to overuse of API's the call bomb is currently down. Actually, both weren't separate features. But executing a bomb on a victim brought in both attacks (SMSs & Calls) simultaneously. In search of a better API, hoping for the best.

**Comment by Amolmeh** [comment]
Ok all the best , your efforts are really awesome i have become a fan of
your work could you also add a text section that would be cool

**Comment by utsanjan** [comment]
OK, I will try my best to achieve that too, and a separate "only call bombing section" is also under process.

**Comment by KodKobra** [comment]
Can you please add call bomb? Hope you got a good API.
