### ISSUE TITLE
Ads not closeable

### ISSUE THREAD

**Issue by Yehh22** [utsanjan/Tsunami-Bomber-Android#13]
When I click close, it always open Play Store. Can you fix it? I can't find a way to access the app properly.

![image](https://github.com/utsanjan/Tsunami-Bomber-Android/assets/127546925/94386c4f-7c78-478f-8c14-dc6fb69cc27b)

**Comment by utsanjan** [comment]
Fixed for now. Do let me know if you face any more issues.
