### ISSUE TITLE
Numbers are double time entered

### ISSUE THREAD

**Issue by Patturajan** [utsanjan/Tsunami-Bomber-Android#4]

**Comment by kingwintage** [comment]
Please solve this problem

**Comment by utsanjan** [comment]
I'm working on the same. I'll let you know with a ReadMe update when it gets fixed.

**Comment by utsanjan** [comment]
This bug is fixed now. Let me know if you find any other bugs.

**Comment by kingwintage** [comment]
Bro I can't open the link

**Comment by kingwintage** [comment]
Thanks bro I got it🤟
