### ISSUE TITLE
double press problem

### ISSUE THREAD

**Issue by TeaqariaWTF** [utsanjan/Tsunami-Bomber-Android#6]
There are too many ads in the application. As a developer, I understand you, but there are still too many ads. When choosing, the numbers are written in pairs, for example, I want to press 1, but it is perceived as double and reflected on the screen as 11. When I try to delete it, it gives an error and returns to the beginning.

**Comment by utsanjan** [comment]
The double integer bug is fixed now. Let me know if you find any other bugs.
